"""initial_phone_auth

Revision ID: 915e0b05243e
Revises: 
Create Date: 2026-02-27 21:33:24.755647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915e0b05243e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Add phone_verification to otp_purpose_enum (alembic doesn't auto-detect enum value changes)
    op.execute("ALTER TYPE otp_purpose_enum ADD VALUE IF NOT EXISTS 'phone_verification'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('revoked_tokens_jti_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('revoked_tokens_jti_key'), ['jti'])

    # ### end Alembic commands ###
    # Note: PostgreSQL does not support removing enum values; phone_verification will remain.
