"""Add sos_message to users

Revision ID: 92ccc2be73f7
Revises: add_enum_val
Create Date: 2026-02-19 00:09:52.870582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ccc2be73f7'
down_revision = 'add_enum_val'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sos_message', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sos_message')

    # ### end Alembic commands ###
