"""
One-shot replacement of the danger-trigger blocks in protection_service.py.
Handles the real UTF-8 emoji bytes that live in the file.
Run with:  python3 scripts/_fix_protection.py
"""
import sys

PATH = 'app/services/protection_service.py'

with open(PATH, 'r', encoding='utf-8') as f:
    src = f.read()

orig_len = len(src)

# ══════════════════════════════════════════════════════════════════════════════
# FIX 1 – analyze_sensor_data: replace the old "if is_danger:" trigger block
# ══════════════════════════════════════════════════════════════════════════════
OLD1 = (
    '    if is_danger:\n'
    '        # Check cooldown before triggering SOS\n'
    '        on_cooldown, secs_left = _is_on_cooldown(user_id)\n'
    '        if on_cooldown:\n'
    '            mins_left = (secs_left + 59) // 60\n'
    '            return {\n'
    '                "alert_triggered": False,\n'
    '                "confidence": confidence_danger,\n'
    '                "message": f"Auto SOS rate-limited. Next trigger allowed in {mins_left} min.",\n'
    '                "retry_after_seconds": secs_left\n'
    '            }\n'
    '\n'
    '        # Trigger SOS\n'
    '        from app.services.location_service import get_last_location\n'
    '        last_loc = get_last_location(user_id)\n'
    '        lat = last_loc.latitude if last_loc else 0.0\n'
    '        lng = last_loc.longitude if last_loc else 0.0\n'
    '\n'
    '        trigger_type = SENSOR_TRIGGER_MAP.get(sensor_type, "auto_fall")\n'
    '        alert, msg = trigger_sos(user_id, lat, lng, trigger_type=trigger_type)\n'
    '        _mark_sos_triggered(user_id)\n'
    '\n'
    '        # Send WhatsApp alert (sync so we can capture sandbox errors)\n'
    '        try:\n'
    '            from app.services.whatsapp_service import send_whatsapp_sync\n'
    '            from app.models.trusted_contact import TrustedContact\n'
    '            contacts = TrustedContact.query.filter_by(user_id=user_id).all()\n'
    '            maps_link = f"https://maps.google.com/?q={lat},{lng}"\n'
    '            whatsapp_msg = f"\u26a0 SOS ALERT!\nDanger detected via {sensor_type}!\nConfidence: {int(confidence_danger*100)}%\n\U0001f4cd Location: {maps_link}"\n'
    '            delivery_report = []\n'
    '            for contact in contacts:\n'
    '                result = send_whatsapp_sync(contact.phone, whatsapp_msg)\n'
    '                delivery_report.append({"phone": contact.phone, **result})\n'
    '                if not result["success"]:\n'
    '                    current_app.logger.warning(\n'
    '                        f"Auto SOS WhatsApp failed for {contact.phone} "\n'
    '                        f"[{result[\'status\']}] code={result[\'error_code\']}: {result[\'error_msg\']}"\n'
    '                    )\n'
    '        except Exception as e:\n'
    '            current_app.logger.error(f"WhatsApp alert failed: {e}")\n'
    '            delivery_report = []\n'
    '\n'
    '        return {\n'
    '            "alert_triggered": True,\n'
    '            "alert_id": alert.id if alert else None,\n'
    '            "confidence": confidence_danger,\n'
    '            "delivery_report": delivery_report\n'
    '        }\n'
    '\n'
    '    return {"alert_triggered": False, "confidence": confidence_danger}'
)

NEW1 = (
    '    if is_danger:\n'
    '        # Block auto-SOS when only the uncalibrated file-fallback model is\n'
    '        # loaded.  Only a DB-trained model (produced by /protection/train-model\n'
    '        # on real user data) is reliable enough to trigger an emergency alert.\n'
    '        if not _has_db_model():\n'
    '            current_app.logger.warning(\n'
    '                f"Auto SOS blocked for user {user_id}: no calibrated DB model. "\n'
    '                "Complete calibration and run /protection/train-model first."\n'
    '            )\n'
    '            return {\n'
    '                "alert_triggered": False,\n'
    '                "confidence": confidence_danger,\n'
    '                "message": "Auto SOS suspended: model not calibrated. Complete calibration first.",\n'
    '                "trigger_reason": "model_not_calibrated"\n'
    '            }\n'
    '\n'
    '        # Fresh DB check \u2014 guards against race conditions where the user\n'
    '        # disarmed between the top-of-function cache check and here.\n'
    '        from app.models.settings import UserSettings\n'
    '        fresh_settings = UserSettings.query.filter_by(user_id=user_id).first()\n'
    '        if not (fresh_settings and fresh_settings.auto_sos_enabled):\n'
    '            current_app.logger.info(\n'
    '                f"Auto SOS suppressed for user {user_id}: "\n'
    '                "system disarmed (fresh DB check caught race with cache)."\n'
    '            )\n'
    '            return {"alert_triggered": False, "confidence": confidence_danger,\n'
    '                    "message": "Auto SOS suppressed: system is disarmed."}\n'
    '\n'
    '        # Check cooldown before triggering SOS\n'
    '        on_cooldown, secs_left = _is_on_cooldown(user_id)\n'
    '        if on_cooldown:\n'
    '            mins_left = (secs_left + 59) // 60\n'
    '            return {\n'
    '                "alert_triggered": False,\n'
    '                "confidence": confidence_danger,\n'
    '                "message": f"Auto SOS rate-limited. Next trigger allowed in {mins_left} min.",\n'
    '                "retry_after_seconds": secs_left\n'
    '            }\n'
    '\n'
    '        # Resolve GPS coordinates\n'
    '        from app.services.location_service import get_last_location\n'
    '        last_loc = get_last_location(user_id)\n'
    '        lat = last_loc.latitude if last_loc else 0.0\n'
    '        lng = last_loc.longitude if last_loc else 0.0\n'
    '\n'
    '        trigger_type = SENSOR_TRIGGER_MAP.get(sensor_type, "auto_fall")\n'
    '        trigger_reason = (\n'
    '            "Unusual fall detected" if sensor_type == "accelerometer"\n'
    '            else "Unusual shake/motion detected"\n'
    '        )\n'
    '        # Embed the trigger reason in the alert\'s SOS message so it appears\n'
    '        # in the WhatsApp notification when dispatch_sos is called.\n'
    '        trigger_prefix = (\n'
    '            f"\u26a0\ufe0f AUTO-SOS: {trigger_reason} ({int(confidence_danger * 100)}% confidence)\\n"\n'
    '            f"Sensor: {sensor_type} | System was armed at time of trigger"\n'
    '        )\n'
    '        alert, msg = trigger_sos(user_id, lat, lng, trigger_type=trigger_type,\n'
    '                                  trigger_prefix=trigger_prefix)\n'
    '        _mark_sos_triggered(user_id)\n'
    '\n'
    '        current_app.logger.warning(\n'
    '            f"Auto SOS triggered for user {user_id}: {trigger_reason} "\n'
    '            f"confidence={confidence_danger:.2f} sensor={sensor_type}"\n'
    '        )\n'
    '\n'
    '        # Dispatch immediately via the standard dispatch_sos path so that:\n'
    '        # 1. Alert status transitions countdown -> sent (visible correctly in history)\n'
    '        # 2. WhatsApp body includes the trigger reason (via trigger_prefix in sos_message)\n'
    '        # 3. Delivery errors are captured in delivery_report\n'
    '        delivery_report = []\n'
    '        if alert:\n'
    '            _, _, delivery_report = dispatch_sos(alert.id, user_id)\n'
    '\n'
    '        return {\n'
    '            "alert_triggered": True,\n'
    '            "alert_id": alert.id if alert else None,\n'
    '            "confidence": confidence_danger,\n'
    '            "trigger_reason": trigger_reason,\n'
    '            "delivery_report": delivery_report\n'
    '        }\n'
    '\n'
    '    return {"alert_triggered": False, "confidence": confidence_danger}'
)

if OLD1 in src:
    src = src.replace(OLD1, NEW1, 1)
    print("FIX 1 applied  ✅")
else:
    print("FIX 1 NOT FOUND ❌")
    idx = src.find('if is_danger:')
    if idx != -1:
        print("  Snippet around 'if is_danger:':")
        print(repr(src[idx:idx+400]))
    else:
        print("  'if is_danger:' not found at all!")
    sys.exit(1)

# ══════════════════════════════════════════════════════════════════════════════
# FIX 2 – predict_from_window: replace the old "if prediction == 1:" block
# ══════════════════════════════════════════════════════════════════════════════
OLD2 = (
    '    if prediction == 1:\n'
    '        # Check cooldown\n'
    '        on_cooldown, secs_left = _is_on_cooldown(user_id)\n'
    '        if on_cooldown:\n'
    '            mins_left = (secs_left + 59) // 60\n'
    '            response["sos_sent"] = False\n'
    '            response["message"] = f"Auto SOS rate-limited. Next trigger allowed in {mins_left} min."\n'
    '            response["retry_after_seconds"] = secs_left\n'
    '            return response\n'
    '\n'
    '        # Resolve coordinates: prefer device-supplied GPS, fall back to DB\n'
    '        if latitude is not None and longitude is not None:\n'
    '            lat, lng = latitude, longitude\n'
    '        else:\n'
    '            from app.services.location_service import get_last_location\n'
    '            last_loc = get_last_location(user_id)\n'
    '            lat = last_loc.latitude if last_loc else 0.0\n'
    '            lng = last_loc.longitude if last_loc else 0.0\n'
    '\n'
    '        trigger_type = SENSOR_TRIGGER_MAP.get(sensor_type, "auto_fall")\n'
    '        alert, msg = trigger_sos(user_id, lat, lng, trigger_type=trigger_type)\n'
    '        _mark_sos_triggered(user_id)\n'
    '\n'
    '        # Send WhatsApp alert (sync so we can capture sandbox errors)\n'
    '        try:\n'
    '            from app.services.whatsapp_service import send_whatsapp_sync\n'
    '            from app.models.trusted_contact import TrustedContact\n'
    '            contacts = TrustedContact.query.filter_by(user_id=user_id).all()\n'
    '            maps_link = f"https://maps.google.com/?q={lat},{lng}"\n'
    '            whatsapp_msg = (\n'
    '                f"\u26a0 SOS ALERT!\nDanger detected via {sensor_type}!\n"\n'
    '                f"Confidence: {int(confidence*100)}%\n"\n'
    '                f"\U0001f4cd Location: {location}\n\U0001f5fa Map: {maps_link}"\n'
    '            )\n'
    '            delivery_report = []\n'
    '            for contact in contacts:\n'
    '                result = send_whatsapp_sync(contact.phone, whatsapp_msg)\n'
    '                delivery_report.append({"phone": contact.phone, **result})\n'
    '                if not result["success"]:\n'
    '                    current_app.logger.warning(\n'
    '                        f"Auto SOS WhatsApp failed for {contact.phone} "\n'
    '                        f"[{result[\'status\']}] code={result[\'error_code\']}: {result[\'error_msg\']}"\n'
    '                    )\n'
    '        except Exception as e:\n'
    '            current_app.logger.error(f"WhatsApp alert failed: {e}")\n'
    '            delivery_report = []\n'
    '\n'
    '        response["sos_sent"] = True\n'
    '        response["alert_id"] = alert.id if alert else None\n'
    '        response["message"] = msg\n'
    '        response["delivery_report"] = delivery_report\n'
    '\n'
    '    else:\n'
    '        response["sos_sent"] = False\n'
    '\n'
    '    return response'
)

NEW2 = (
    '    if prediction == 1:\n'
    '        # Block auto-SOS when only the uncalibrated file-fallback model is loaded.\n'
    '        if not _has_db_model():\n'
    '            current_app.logger.warning(\n'
    '                f"Auto SOS (predict) blocked for user {user_id}: no calibrated DB model."\n'
    '            )\n'
    '            response["sos_sent"] = False\n'
    '            response["message"] = "Auto SOS suspended: model not calibrated. Complete calibration first."\n'
    '            response["trigger_reason"] = "model_not_calibrated"\n'
    '            return response\n'
    '\n'
    '        # Fresh DB check \u2014 guards against the user disarming between the\n'
    '        # top-of-function cache check and this point (race condition).\n'
    '        from app.models.settings import UserSettings\n'
    '        fresh_settings = UserSettings.query.filter_by(user_id=user_id).first()\n'
    '        if not (fresh_settings and fresh_settings.auto_sos_enabled):\n'
    '            current_app.logger.info(\n'
    '                f"Auto SOS (predict) suppressed for user {user_id}: "\n'
    '                "system disarmed (fresh DB check)."\n'
    '            )\n'
    '            response["sos_sent"] = False\n'
    '            response["message"] = "Auto SOS suppressed: system is disarmed."\n'
    '            return response\n'
    '\n'
    '        # Check cooldown\n'
    '        on_cooldown, secs_left = _is_on_cooldown(user_id)\n'
    '        if on_cooldown:\n'
    '            mins_left = (secs_left + 59) // 60\n'
    '            response["sos_sent"] = False\n'
    '            response["message"] = f"Auto SOS rate-limited. Next trigger allowed in {mins_left} min."\n'
    '            response["retry_after_seconds"] = secs_left\n'
    '            return response\n'
    '\n'
    '        # Resolve coordinates: prefer device-supplied GPS, fall back to DB\n'
    '        if latitude is not None and longitude is not None:\n'
    '            lat, lng = latitude, longitude\n'
    '        else:\n'
    '            from app.services.location_service import get_last_location\n'
    '            last_loc = get_last_location(user_id)\n'
    '            lat = last_loc.latitude if last_loc else 0.0\n'
    '            lng = last_loc.longitude if last_loc else 0.0\n'
    '\n'
    '        trigger_type = SENSOR_TRIGGER_MAP.get(sensor_type, "auto_fall")\n'
    '        trigger_reason = (\n'
    '            "Unusual fall detected" if sensor_type == "accelerometer"\n'
    '            else "Unusual shake/motion detected"\n'
    '        )\n'
    '        # Embed the trigger reason in the alert\'s SOS message so it appears\n'
    '        # in the WhatsApp notification when /send-now -> dispatch_sos fires.\n'
    '        trigger_prefix = (\n'
    '            f"\u26a0\ufe0f AUTO-SOS: {trigger_reason} ({int(confidence * 100)}% confidence)\\n"\n'
    '            f"Sensor: {sensor_type} | Location: {location} | System was armed"\n'
    '        )\n'
    '        alert, msg = trigger_sos(user_id, lat, lng, trigger_type=trigger_type,\n'
    '                                  trigger_prefix=trigger_prefix)\n'
    '        _mark_sos_triggered(user_id)\n'
    '\n'
    '        current_app.logger.warning(\n'
    '            f"Auto SOS (predict) countdown started for user {user_id}: "\n'
    '            f"{trigger_reason} confidence={confidence:.2f} sensor={sensor_type}"\n'
    '        )\n'
    '\n'
    '        # Do NOT dispatch (send WhatsApp) here.\n'
    '        # The frontend receives the alert_id and shows a cancellation countdown.\n'
    '        # If not cancelled, the frontend calls /sos/send-now which invokes\n'
    '        # dispatch_sos \u2014 this ensures:\n'
    '        #   \u2022 Alert status correctly transitions countdown -> sent in history\n'
    '        #   \u2022 WhatsApp body includes the trigger reason (stored in sos_message)\n'
    '        #   \u2022 No double-dispatch (contacts previously received TWO messages)\n'
    '        response["sos_sent"] = True\n'
    '        response["alert_id"] = alert.id if alert else None\n'
    '        response["message"] = msg\n'
    '        response["trigger_reason"] = trigger_reason\n'
    '        response["countdown_seconds"] = current_app.config.get("SOS_COUNTDOWN_SECONDS", 10)\n'
    '\n'
    '    else:\n'
    '        response["sos_sent"] = False\n'
    '\n'
    '    return response'
)

if OLD2 in src:
    src = src.replace(OLD2, NEW2, 1)
    print("FIX 2 applied  ✅")
else:
    print("FIX 2 NOT FOUND ❌")
    idx = src.find('if prediction == 1:')
    if idx != -1:
        print("  Snippet around 'if prediction == 1:':")
        print(repr(src[idx:idx+400]))
    else:
        print("  'if prediction == 1:' not found at all!")
    sys.exit(1)

with open(PATH, 'w', encoding='utf-8') as f:
    f.write(src)

print(f"\nFile written. Size {orig_len} -> {len(src)} bytes.")
